# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2016-09-22 00:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad_fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_localidad', models.CharField(max_length=80)),
                ('censo', models.IntegerField()),
                ('poblacion', models.IntegerField()),
                ('viviendas', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.Localidad')),
            ],
            options={
                'db_table': 'g_localidad_fuente',
            },
        ),
    ]
