# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2016-09-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0002_localidad_fuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.Asiento')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.Subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Recinto_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.Recinto')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.Subcategoria')),
            ],
        ),
    ]
