# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0003_asiento_detalle_recinto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continente',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
